### ISSUE TITLE
[Dashboard] Formatted reports include html

### ISSUE THREAD

**Issue by mfitz3** [HazyResearch/mindbender#11]
At least with many of the sample reports in the stanford-memex data, the API call to GET api/snapshot/snapshotId/reportId includes an "html" key for formatted reports. This makes it difficult to determine formatted from custom reports, as this determination is based on whether the "html" key is present in the report JSON.

Example:
/api/snapshot/20150410-6/variable/candidate/sample-frequent-candidates%20rates.is_correct

The resulting JSON includes a "chart" key under the first data key, suggesting that it is a formatted report, but also includes an "html" key.

**Comment by netj** [comment]
I believe this was fixed in https://github.com/HazyResearch/mindbender/commit/dfe0cc0cef2634c1a419abbf3bb9f8aa075ff5e6#diff-781d33b2e2f407944b2d95dea760dd57.  The example data generated with previous code was probably producing spurious JSON.
