### ISSUE TITLE
[Dashboard] Calibration plot contains empty strings

### ISSUE THREAD

**Issue by mfitz3** [HazyResearch/mindbender#12]
The JSON file for the calibration plot report contains empty strings. These empty strings should probably be zeros.

**Comment by netj** [comment]
Empty strings are coming from the node-csv parser we use in the backend, and it's a bit tricky to eliminate them completely.  We now have a fairly robust data normalization step that's taking care of them (https://github.com/HazyResearch/mindbender/commit/fcf5e4d5e326e84065cdbf2d636945a5afdfaa15#diff-154b33f3346204ec11f12e8395273e14R337), so I believe this won't be a issue anymore.
