### ISSUE TITLE
Cannot run deepdive in examples/spouse_example folder 

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/mindbender#44]
In the README.md, it said we can run spouse example based on following cmds:
cd examples/spouse_example
deepdive initdb
deepdive run

Btw: the path is wrong. Can you clarify it?

**Comment by netj** [comment]
[examples/spouse_example](https://github.com/HazyResearch/mindbender/tree/master/examples/spouse_example) is a deepdive app.  You should have `deepdive` as well as `mindbender` commands on your `PATH` environment.

**Comment by SenWu** [comment]
In the README.md, I suppose to run mindbender with current deepdive spouse application, but that application is not in that directory (it's in its subdirectory?).

**Comment by SenWu** [comment]
Am I missing something? This application is mindbender application instead of Deepdive application?

**Comment by netj** [comment]
If you follow the link I commented, I think everything's pretty clear.  To clarify: There's nothing like a mindbender app.  Here in mindbender repo, we keep a copy of the spouse example to demonstrate the tools.  The spouse example in ddlog under deepdive source tree should also work fine with mindbender, but you won't get the search UI until you manually annotate it as done in https://github.com/HazyResearch/mindbender/blob/master/examples/spouse_example/app.ddlog.

One catch is that deepdive's master just got a ddlog compiler update, so there might be some parse errors if you use the wrong combination.  I'll push a commit that updates the ddlog syntax used in the mindbender copy.
