### ISSUE TITLE
invalid mindbender COMMAND

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/mindbender#45]
I am using the latest version of Deepdive. I tried to use the following cmds in the README.md, but got the following issues:
$ mindbender search update
\# mindbender shell
\# Usage: mindbender [-OPTION] COMMAND [ARG]...

\# Global OPTION is one of:
\#   -v      increase verbosity
\#   -q      suppress all messages
\#   -t      force logging to non-ttys
\#           (default is to log messages to stderr only when it's a tty)

search: invalid COMMAND

$ mindbender search gui
\# mindbender shell
\# Usage: mindbender [-OPTION] COMMAND [ARG]...

\# Global OPTION is one of:
\#   -v      increase verbosity
\#   -q      suppress all messages
\#   -t      force logging to non-ttys
\#           (default is to log messages to stderr only when it's a tty)

search: invalid COMMAND

Did I try something wrong?

**Comment by netj** [comment]
You need to download the latest from https://github.com/HazyResearch/mindbender/releases/tag/LATEST.  The one you're running is probably the one released or pointed by deepdive, and it's a farily old version that does not contain search yet.
