### ISSUE TITLE
Support @searchable for text[]?

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/mindbender#46]
I try @searchable for a column with text type and it works fine. 
But when I try to @searchable for a column with text[] type, it doesn't work and displays some other information, e.g., NER, POS, LEMMA...etc...
Do we support @searchable for text[]?

**Comment by netj** [comment]
Everything in the relation becomes searchable regardless of its type. `@searchable` annotation just determines whether the string values should be tokenized or treated as a whole. If you meant rendering the result, you should use the mindbender/search-template/*.html stuff. There are some in the spouse_example.
