### ISSUE TITLE
Spouse example does not work with latest DeepDive/ddlog

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/mindbender#51]
```
[error] app.ddlog[67.26] failure: `(' expected but `l' found

function ext_people over like ext_people_input

                         ^
```

The example is different from the example in the ddlog repository. Did the syntax change?

**Comment by SenWu** [comment]
Yes. Here is the new syntax for tsv extractor:
function XXX over rows like YYY
  returns rows like ZZZ
  implementation AAA handles tsv lines.

**Comment by chrismre** [comment]
@zhangce @netj This has got to be fixed in the docs! (is it) :)

**Comment by netj** [comment]
@raphaelhoffmann Yes the syntax changed and I made the changes but forgot to push.  Just updated.
@chrismre The website is up to date.  This issue is about the example hidden in mindbender repo for demonstrating DDlog annotations and frontend tools.
