### ISSUE TITLE
is_correct counts disappear after restarting mindtagger

### ISSUE THREAD

**Issue by xiaoling** [HazyResearch/mindbender#54]
I suppose mindtagger reloads the annoatations from tags.json every time it restarts. The is_correct annotations are still there but the distribution of is_correct values is missing. Please see the attached screenshot. -Xiao
![screen shot 2015-09-29 at 7 13 32 pm](https://cloud.githubusercontent.com/assets/474885/10182872/59ef47b6-66de-11e5-8b61-1c34a3103190.png)

**Comment by xiaoling** [comment]
Ok. I noticed that my tags.json file contained additional annotations on the instances other than the ones in input.csv . After I removed these annotations, the is_correct stats re-appeared.

**Comment by zhangce** [comment]
@xiaoling Sorry for the late reply--I think @netj is traveling right now and we will get back to you later today.

**Comment by netj** [comment]
@xiaoling @raphaelhoffmann Sorry this took so long!
