### ISSUE TITLE
How to change ip:port config to run mindbender in a server?

### ISSUE THREAD

**Issue by RominYue** [HazyResearch/mindbender#78]
Actually I install deepdive in an ubuntu server without GUI. The command "mindbender search gui" runs at localhost:8000 and may elasticsearch runs at localhost...How do I change config files that can run by ip:port like 194.1.168.3:8000?

**Comment by alldefector** [comment]
You could use something like `PORT=9000 mindbender search gui` to specify the port. Mindbender doesn't restrict allowed hosts, so you should be able to visit it from a remote machine, as long as the mindbender machine's PORT is accessible by the remote machine per the firewall.
